### ISSUE TITLE
`Command failed: pnpm install glob`

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/quokka#160]
### Issue description or question

The link `Install "glob" package for the current quokka file` appears. I click the link. Then I see this message with no way to debug:

```
Command failed: pnpm install glob
```

Maybe something to do with the `PATH` env var that is used to run the command?

### Sample code

```javascript
import glob from 'glob'
```

### Config

```
{
  "pro": true,
  "babel": true,
  "plugins": [],
  "installPackageCommand": "pnpm install {packageName}"
}
```

### Quokka.js Console Output

```
Quokka #1 (node: v8.9.0, babel: v6.24.1)

Command failed: pnpm install glob
```

### Code editor version

Visual Studio Code v1.?
IntelliJ v2018.1 EAP
Atom v1.?

### OS name and version

Windows
**OSX**
Linux

**Comment by vjpr** [comment]
I check in `~/.quokka/data/byyd6/pnpm-debug.log` and see this:

```
---
  0 error pnpm: 
    message: 
      errno: -2
      code: "ENOENT"
      syscall: "open"
      path: "/Users/Vaughan/.quokka/data/byyd6/package.json"
    err: 
      name: "Error"
      message: "ENOENT: no such file or directory, open '/Users/Vaughan/.quokka/data/byyd6/package.json'"
      code: "ENOENT"
      stack: "Error: ENOENT: no such file or directory, open '/Users/Vaughan/.quokka/data/byyd6/package.json'"
```
