### ISSUE TITLE
Atom: Add quokka-specific class(s) to inline comment elements.

### ISSUE THREAD

**Issue by metasean** [wallabyjs/quokka#87]
### Description [Feature Request]

Add a quokka-specific selector class(s) to inline comments for custom CSS styling.

Currently output is using the same classes as other comments (e.g. `syntax--comment` `syntax--line`, `syntax--double-slash`, `syntax--js`, `syntax--punctuation`, `syntax--definition`, `syntax-block`)  so there's no way to style _just_ quokka elements.

### Example
From:
```
<span class="syntax--punctuation syntax--definition syntax--comment syntax--js">//</span>
```

To:
```
<span class="quokka syntax--punctuation syntax--definition syntax--comment syntax--js">//</span>
             ⬆︎⬆⬆︎
```

**Comment by metasean** [comment]
I think I figured out how to do what I wanted, but I'm going to leave this open in case there is a more precise way to select _just the quokka comment_ (e.g. my example above). After having figured out the code below, I'm assuming there isn't a way to implement a more precise selection - if this assumption is correct, please close this issue.

```css
/******************************************************************************
                                      _      _
               __ _   _   _    ___   | | __ | | __   __ _
              / _` | | | | |  / _ \  | |/ / | |/ /  / _` |
             | (_| | | |_| | | (_) | |   <  |   <  | (_| |
              \__, |  \__,_|  \___/  |_|\_\ |_|\_\  \__,_|
                 |_|
*******************************************************************************/

/* ANY comment on the same line as Quokka inline results */
.qlc .syntax--comment {
  padding-left: 0.25ex;
  background-color: #9d9da5;
  color: #1c1c3f;
}

/* The invisible eol for any line with Quokka inline results */
.qlc .syntax--comment + .invisible-character.eol {
  background-color: #9d9da5;
  color: #9d9da5;
}

/* actual Quokka inline result */
.atom-text-editor .line.qlc::after,
atom-text-editor .line.qlc::after {
  padding-right: 1ex;
  background-color: #9d9da5;
  color: #1c3f1c;
}

```

p.s. Obviously, others are probably going to want different values.  These values were generally what I wanted for my [Atom Dracula Black](https://atom.io/themes/atom-dracula-black) theme.

**Comment by ArtemGovorov** [comment]
We don't a control over the `span`s that Atom generates (can only add classes to line `div`s), however, you have already provided the nice way to style inline comment elements.

So for inline comment styling one may use:

```css
.atom-text-editor .line.qlc::after, atom-text-editor .line.qlc::after {
    color: ...;
}
```
and for inline error messages:
```css
.atom-text-editor .line.qle::after, atom-text-editor .line.qle::after {
    color: #c00;
}
```
